spring:
  datasource:
    url: jdbc:mysql://xxx:3306/xxx?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123

logging:
  com:
    elijah:
      permissionhelper:
        level: debug